config/routes.rb
Rails.application.routes.draw do
  get 'pages/splash'
  get 'pages/about'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  devise_scope :user do
    authenticated :user do
      root :to => 'groups#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'pages#splash', as: :unauthenticated_root
    end
  end

  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :purchases
  end

  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_purchases, dependent: :destroy
  has_many :purchases, through: :group_purchases

  belongs_to :user

  validates :name, presence: true, length: { maximum: 36 },
                   uniqueness: { scope: :user, message: 'user already has this group' }
  validates :icon, presence: true, length: { maximum: 250 }
end

app/models/group_purchase.rb
class GroupPurchase < ApplicationRecord
  belongs_to :group
  belongs_to :purchase

  validates :purchase, uniqueness: { scope: :group }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :group_purchases, dependent: :destroy
  has_many :groups, through: :group_purchases
  accepts_nested_attributes_for :group_purchases, allow_destroy: true
  # belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 36 }
  validates :amount, presence: true, numericality: { money: true, greater_than_or_equal_to: 0 }
  validates_associated :group_purchases
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :purchases, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { maximum: 36 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/group_purchases_controller.rb
class GroupPurchasesController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      flash[:success] = 'Category created successfully!'
      redirect_to groups_path
    else
      flash.now[:error] = @group.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:success] = 'Category updated successfully!'
      redirect_to group_purchases_path(@group)
    else
      flash.now[:error] = @group.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      flash[:success] = 'Category was deleted successfully!'
      redirect_to groups_url
    else
      flash[:error] = @group.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:splash]

  def splash; end

  def about; end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @purchases = @group.purchases.order(id: :desc)
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = current_user.purchases.new(purchase_params.except(:group_ids))
    @groups = Group.where(id: purchase_params[:group_ids])
    if @groups.empty?
      flash.now[:error] = 'You must choose at least one category!'
      render :new
    elsif @purchase.save
      @groups.each do |group|
        group.purchases << @purchase
      end
      flash[:success] = "Transaction was created and added to #{@groups.length} goups!"
      redirect_to group_purchases_path(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @purchase = Purchase.find(params[:id])
  end

  def update
    @purchase = Purchase.find(params[:id])
    @groups = Group.where(id: purchase_params[:group_ids])
    if @groups.empty?
      flash.now[:error] = 'You must choose at least one category!'
      render :edit
    elsif @purchase.update(purchase_params.except(:group_ids))
      @purchase.groups.delete_all
      @groups.each do |group|
        group.purchases << @purchase unless group.purchases.include?(@purchase)
      end
      flash[:succes] = 'Transaction updated successfully!'
      redirect_to group_purchases_path(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    if @purchase.destroy
      flash[:success] = 'Transaction was deleted successfully!'
      redirect_to group_purchases_url(params[:group_id])
    else
      flash.now[:error] = @purchase.errors.full_messages.to_sentence
      render :show
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < Application.rb
  def show; end

  def edit; end
  
  def update; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.erb
<header>
  <%= link_to group_purchases_path(params[:id]), data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>edit category</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions for_form">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  <%= form_with model: @group, class: "form" do |f| %>
    <div class="field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Clothes" %>
    </div>

    <div class="field">
      <%= f.label :icon, "Icon link *" %>
      <%= f.text_field :icon, autofocus: true, autocomplete: "icon", placeholder: "https://i.pravatar.cc/300?img=5" %>
    </div>

    <p>* Please, provide a valid link that starts with <strong>'https:'</strong> and ends with <strong>'png/gif/jpg'</strong>.</p>

    <div class="actions">
      <%= f.submit "update", data: { turbo: false }, class: "btn" %>
    </div>
  <% end %>
</main>

app/views/groups/index.html.erb
<header id="homepage">
  <h1>categories</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <% if @groups.empty? %>
    <div class="empty">
      <p>You have not added any categories.</p>
    </div>
  <% end %>

  <ul class="group_list">
    <% @groups.each do |group| %>
      <% total_amount = total_amount(group) %>
      <li>
        <%= link_to group_purchases_url(group), data: { turbo: false }, class: 'item' do %>
          <%= image_tag(check_url(group.icon), class: 'icon', alt: 'group_icon') %>
          <div class="group_info">
            <span class="name"><%= group.name %></span>
            <span class="amount">$<%= total_amount %></span>
            <span class="date"><%= group.created_at.strftime('%d %b %Y') %></span>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</main>

<section id="actions">
  <%= link_to "add category", new_group_path, class: "btn", data: { turbo: false }  %>
</section>

app/views/groups/new.html.erb
<header>
  <%= link_to groups_path, data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>new category</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions for_form">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  <%= form_with model: @group, class: "form" do |f| %>
    <div class="field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Clothes" %>
    </div>

    <div class="field">
      <%= f.label :icon, "Icon link *" %>
      <%= f.text_field :icon, autofocus: true, autocomplete: "icon", placeholder: "https://i.pravatar.cc/300?img=5" %>
    </div>

    <p>* Please, provide a valid link that starts with <strong>'https:'</strong> and ends with <strong>'png/gif/jpg'</strong>.</p>

    <div class="actions">
      <%= f.submit "add category", data: { turbo: false }, class: "btn" %>
    </div>
  <% end %>
</main>

app/views/groups/show.html.erb
<h1>Show group details</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'pages/menu' %>

    <%= yield %>
  </body>
</html>

app/views/pages/_menu.html.erb
<div id="menu" class='hidden'>
  <nav>
    <% if current_user %>
      <div class='user_info'>
        <span>
          <%= current_user.name %>
        </span>
        <span>
          <%= current_user.email %>
        </span>
      </div>
    <% end %>
    <ul>
      <li>
        <%= inline_svg_tag "settings.svg", class: "menu_icons" %>
        <a href="#">Account settings</a>
      </li>
      <li>
        <%= inline_svg_tag "settings.svg", class: "menu_icons" %>
        <a href="#">All purchases</a>
      </li>
      <li>
        <%= inline_svg_tag "about.svg", class: "menu_icons" %>
        <a href="#">About</a>
      </li>
      <li>
        <%= inline_svg_tag "sign_out.svg", class: "menu_icons" %>
        <% if current_user %>
          <%= link_to "Sign out", destroy_user_session_path,
          data: { turbo_method: :delete} %>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </li>
    </ul>
  <nav>
</div>

app/views/pages/about.html.erb
<header>
  <%= link_to groups_path, data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>about</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="splash">
  <p>Find me in app/views/pages/about.html.erb</p>
</main>

app/views/pages/splash.html.erb
<main class="splash">
  <section class="wallpaper">
    <h1>SmartPocket</h1>
  </section>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <section>
    <%= link_to "log in", new_user_session_path, data: { turbo: false } %>
    <%= link_to "sign up", new_user_registration_path, data: { turbo: false } %>
  </section>
</main>

app/views/purchases/edit.html.erb
<header>
  <%= link_to group_purchases_path(params[:group_id]), data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>edit transaction</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions for_form">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <%= form_with(url: group_purchase_path, model: @purchase, method: :patch, class: "form") do |f| %>
    <div class="field">
      <%= f.label :name, "name" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Bodyshop cream" %>
    </div>

    <div class="field">
      <%= f.label :amount, "amount, $" %>
      <%= f.text_field :amount, autofocus: true, autocomplete: "amount", placeholder: "15" %>
    </div>

    <div class="checkbox">
      <%= f.label :amount, "choose categories:" %><br />
      <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :name, :include_hidden => false %>
      <span>No mathing category?</span>
      <%= link_to "add a new category", new_group_path, data: { turbo: false }, class: "static"  %>
    </div>

    <div id="actions">
      <%= f.submit "update", data: { turbo: false }, class: "btn"  %>
    </div>
  <% end %>
</main>

app/views/purchases/index.html.erb
<header>
  <%= link_to groups_path, data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>transactions</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <div class='top_category'>
    <%= link_to edit_group_url(@group), data: { turbo: false }, class: 'item' do %>
      <%= image_tag(check_url(@group.icon), class: 'icon', alt: 'group_icon') %>
      <div class="group_info">
        <span class="name"><%= @group.name %></span>
        <span class="amount">$<%= total_amount(@group)%></span>
        <span class="date"><%= @group.created_at.strftime('%d %b %Y') %></span>
      </div>
    <% end %>
  </div>

  <% if @purchases.empty? %>
    <div class="empty">
      <p>Group has no transactions.</p>
    </div>
  <% end %>

  <ul class="purchase_list">
    <% @purchases.includes([:groups]).each do |purchase| %>
      <li>
        <%= link_to group_purchase_url(@group, purchase), data: { turbo: false }, class: "item purchase" do %>
          <div class="group_info no_margin">
            <span class="name"><%= purchase.name %></span>
            <span class="amount">$<%= purchase.amount %></span>
            <div class="date">
              <%= inline_svg_tag "calendar.svg", class: "calendar" %>
              <%= purchase.created_at.strftime('%d %b %Y') %>
            </div>
          </div>
        <% end %>
        <ul class="item associated_categories">
          <% purchase.groups.each do |group| %>
            <li class="associated_category">
              <%= image_tag(check_url(group.icon), class: 'icon', alt: 'group_icon') %>
              <span><%= group.name %></span>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</main>

<section id="actions">
  <% if @purchases.empty? %>
    <%= button_to "delete category", {:controller => :groups, :action => 'destroy', :id => @group.id }, :method => :delete, data: { turbo: false }, class: "btn blue_action" %>
    <%= link_to "add transaction", new_group_purchase_path, class: "btn upper_action", data: { turbo: false }  %>
  <% else %>
    <%= link_to "add transaction", new_group_purchase_path, class: "btn", data: { turbo: false }  %>
  <% end %>
</section>

app/views/purchases/new.html.erb
<header>
  <%= link_to group_purchases_path(params[:group_id]), data: { turbo: false }  do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>new transaction</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_actions for_form">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <%= form_with(url: group_purchases_path, model: @purchase, class: "form") do |f| %>
    <div class="field">
      <%= f.label :name, "name" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Bodyshop cream" %>
    </div>

    <div class="field">
      <%= f.label :amount, "amount, $" %>
      <%= f.text_field :amount, autofocus: true, autocomplete: "amount", placeholder: "15" %>
    </div>

    <div class="checkbox">
      <%= f.label :amount, "categories", class: "categories_label" %><br />
      <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :name, :include_hidden => false %>
      <span>No mathing category?</span>
      <%= link_to "add a new category", new_group_path, data: { turbo: false }, class: "static"  %>
    </div>

    <div id="actions">
      <%= f.submit "add transaction", data: { turbo: false }, class: "btn"  %>
    </div>
  <% end %>
</main>

app/views/purchases/show.html.erb
<header>
  <%= link_to group_purchases_path(params[:group_id]), data: { turbo: false } do %>
    <%= inline_svg_tag "chevron_left.svg", class: "chevron" %>
  <% end %>
  <h1>details</h1>
  <div id="whatever">
    <%= inline_svg_tag "menu.svg", class: "burger-menu" %>
  </div>
</header>

<main class="with_two_actions">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  <div class="item purchase">
    <div class="group_info no_margin">
      <span class="name"><%= @purchase.name %></span>
      <span class="amount">$<%= @purchase.amount %></span>
      <div class="date">
        <%= inline_svg_tag "calendar.svg", class: "calendar" %>
        <%= @purchase.created_at.strftime('%d %b %Y') %>
      </div>
    </div>
  </div>
  <ul class="item associated_categories">
    <% @purchase.groups.each do |group| %>
      <li class="associated_category">
        <%= image_tag(check_url(group.icon), class: 'icon', alt: 'group_icon') %>
        <span><%= group.name %></span>
      </li>
    <% end %>
  </ul>
</main>

<section id="actions">
  <%= link_to "edit", edit_group_purchase_path(params[:group_id], @purchase), data: { turbo: false }, class: "btn upper_action" %>
  <%= button_to "delete",  {:controller => :purchases, :action => 'destroy'}, method: :delete, data: { turbo: false }, class: "btn blue_action"  %>
</section>